[gutarik]
project_dirs = ["app", "tests"]
docs_dir = "docs"
supported_ext = [".py"]
wiki_repo = "https://github.com/SLUT-Science-Learning-Unity-Trolling/Chalkboard-OCR-Classification-Kit/wiki.git"
local_wiki_dir = ".wiki_tmp"
exclude_dirs = []