site_name: Chalkboard OCR Classification Kit
site_description: Документация проекта Chalkboard-OCR-Classification-Kit
site_author: ProudRykar
theme:
  custom_dir: docs/custom_theme
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
    - palette.toggle
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Включить тёмную тему
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/white-balance-sunny
        name: Включить светлую тему
nav:
  - Home: index.md
  - Core: [in_work.md]
  - Errors: [in_work.md]
  - Models: [in_work.md]
  - Schema: [in_work.md]
  - Scripts: [in_work.md]
  - Services: [in_work.md]
  - Utils: [in_work.md]
  - Repositories:
    - RepositoryInterface: repositories/abc_repo.md
    - MongoRepo: repositories/mongo_repo.md
  - Tests: [in_work.md]
  - Graphs: diagrams/diagrams.md
plugins:
  - search  # Если ещё не добавлен, для поиска
  - glightbox  # Плагин для lightbox
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - attr_list  # Для поддержки классов в изображениях
  - md_in_html  # Для HTML в Markdown (если нужно)
  - pymdownx.blocks.caption  # Для подписей под изображениями (опционально)