site_name: Chalkboard OCR Classification Kit
site_description: Документация проекта Chalkboard-OCR-Classification-Kit
site_author: ProudRykar

theme:
  custom_dir: docs/custom_theme
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
    - palette.toggle
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Включить тёмную тему
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/white-balance-sunny
        name: Включить светлую тему

nav:
  - Home: index.md
  - Core:
      - Models:
          - User: core/models/user.md
      - Services:
          - UserService: core/services/user_service.md
  - Errors:
      - User Errors: errors/user.md
  - Schema:
      - UserDTO: schema/user_dto.md
  - Scripts:
      - Clean Project: scripts/clean_project.md
  - Utils: []
  - Repositories:
      - RepositoryInterface: repositories/abc_repo.md
      - MongoRepo: repositories/mongo_repo.md
  - Tests: []
  - Graphs:
      - Overview: diagrams/diagrams.md
      - Business Logic Diagram: diagrams/business_logic_diagram.png
      - Tech Architecture Diagram: diagrams/tech_architecture_diagram.png

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
